app/accounts/urls.py
from django.urls import path
from accounts.views import MyProfileView, SignUpView, ActivateUserView
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [

    path('my-profile/<int:pk>', MyProfileView.as_view(), name='my-profile'),

    path('sign-up/', SignUpView.as_view(), name='sign-up'),
    path('activate/<uuid:username>', ActivateUserView.as_view(), name='activate-user'),

    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),


]

app/currency/urls.py
from currency.views import (IndexView, RateListView, RateCreateView,
                            RateDetailView, RateUpdateView, RateDeleteView, ContactUsCreateView,
                            )


from django.urls import path

app_name = 'currency'

urlpatterns = [

    path('', IndexView.as_view()),

    #Rate
    path('rate/list/', RateListView.as_view(), name='rate-list'),
    path('rate/create/', RateCreateView.as_view(), name='rate-create'),
    path('rate/details/<int:pk>/', RateDetailView.as_view(), name='rate-details'),
    path('rate/update/<int:pk>/', RateUpdateView.as_view(), name='rate-update'),
    path('rate/delete/<int:pk>/', RateDeleteView.as_view(), name='rate-delete'),

    path('contactus/create/', ContactUsCreateView.as_view(), name='contactus-create'),

]

app/settings/urls.py
from currency.views import (ContactUsView,  GeneratePasswordView, IndexView,
                            response_codes, SourceListView, SourceCreateView,
                            SourceUpdateView, SourceDeleteView)

from django.contrib import admin
import debug_toolbar
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', TemplateView.as_view(template_name='index.html'), name='index'),


    path('silk/', include('silk.urls', namespace='silk')),



    path('currency/', include('currency.urls')),
    path('accounts/', include('accounts.urls')),

    path('auth/', include('django.contrib.auth.urls')),


    path('index/', IndexView.as_view(), name='index'),
    path('gen-pass/',  GeneratePasswordView.as_view()),
    path('contact-us/', ContactUsView.as_view(), name='contact-us'),


    path('source/list/', SourceListView.as_view(), name='source-list'),
    path('source/create/', SourceCreateView.as_view(), name='source-create'),
    path('source/update/<int:pk>/', SourceUpdateView.as_view(), name='source-update'),
    path('source/delete/<int:pk>/', SourceDeleteView.as_view(), name='source-delete'),

    path('response-codes/', response_codes),

    path('__debug__/', include(debug_toolbar.urls)),
]

app/currency/models.py
from django.db import models
from django.utils import timezone
from currency import model_choices as mch


class Rate(models.Model):
    sale = models.DecimalField(max_digits=5, decimal_places=2)
    buy = models.DecimalField(max_digits=5, decimal_places=2)
    created = models.DateTimeField(auto_now_add=True)
    source = models.CharField(max_length=32)  # privat, monobank
    type = models.CharField(max_length=3, choices=mch.RATE_TYPES)  # USD, EUR
    display_name = models.CharField(max_length=12)
    # get_{filed_name}_display()


class ContactUs(models.Model):
    created = models.DateTimeField(default=timezone.now())
    id = models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')
    email_form = models.EmailField(max_length=50)
    subject = models.CharField(max_length=255)
    message = models.CharField(max_length=5000)
    email_to = models.EmailField(default='')
    body = models.CharField(max_length=2056, default='')


class Source(models.Model):
    id = models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')
    source_url = models.URLField(max_length=255)
    name = models.CharField(max_length=50)


class ResponseLog(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    status_code = models.PositiveSmallIntegerField()
    path = models.CharField(max_length=255)
    response_time = models.PositiveSmallIntegerField(
        help_text='in milliseconds.'
    )
    request_method = models.CharField(max_length=4, choices=mch.RESPONSELOG_REQUESTS, default='')

app/currency/forms.py
from django import forms

from currency.models import Rate, Source, ContactUs


class RateForm(forms.ModelForm):
    class Meta:
        model = Rate
        fields = (
            'buy',
            'sale',
            'source',
            'type',
        )


class SourceForm(forms.ModelForm):
    class Meta:
        model = Source
        fields = (
            'name',
            'source_url',
        )


class ContactUsForm(forms.ModelForm):
    class Meta:
        model = ContactUs
        fields = (
            'email_form',
            'subject',
            'message',
        )

app/currency/views.py
from django.urls import reverse, reverse_lazy
from currency.tasks import contact_us
from django.http import HttpResponse, HttpResponseRedirect

from currency.utils import generate_password as gen_pass

from currency.models import Rate, ContactUs, Source, ResponseLog
from currency.forms import RateForm, SourceForm, ContactUsForm
from django.views.generic import (
    ListView, CreateView, DetailView,
    UpdateView, DeleteView, View, TemplateView)

from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404


# def index(request):
#     return render(request, 'index.html')


class IndexView(TemplateView):
    template_name = 'index.html'


# def generate_password(request):
#     password_len = int(request.GET.get('password-len'))
#     password = gen_pass(password_len)
#     return HttpResponse(password)


# class GeneratePasswordView(View):
#     def get(self, request):
#         password_len = int(request.GET.get('password-len'))
#         password = gen_pass(password_len)
#         return HttpResponse(password)
#


class GeneratePasswordView(TemplateView):
    template_name = 'generate_password.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        password_len = int(self.request.GET.get('password-len'))
        context['password'] = gen_pass(password_len)
        return context


# def rate_list(request):
#     rates = Rate.objects.all()
#     context = {
#         'rate_list': rates,
#     }
#
#     return render(request, 'rate_list.html', context=context)


class RateListView(ListView):
    queryset = Rate.objects.all().order_by('-created')
    template_name = 'rate_list.html'

    # def get(self, request, *args, **kwargs):
    #     print(request.COOKIES)
    #     return super().get(request, *args, **kwargs)


class ContactUsCreateView(CreateView):
    model = ContactUs
    success_url = reverse_lazy('index')
    template_name = 'contact_us_create.html'
    fields = (
        'email_to',
        'subject',
        'body',
    )

    def form_valid(self, form):
        subject = form.cleaned_data['subject']
        body = form.cleaned_data['body']
        email_to = form.cleaned_data['email_to']

        full_email_body = f'''
        Email from: {email_to}
        Body: {body}
        '''

        contact_us.apply_async(args=(subject,), kwargs={'body': full_email_body})

        return super().form_valid(form)

    def form_invalid(self, form):
        print('form_invalid')
        return super().form_invalid(form)


# def rate_create(request):
#     if request.method == 'POST':
#         form = RateForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect('/rate/list/')
#     elif request.method == 'GET':
#         form = RateForm()
#     context = {
#         'form': form,
#     }
#     return render(request, 'rate_create.html', context=context)


class RateCreateView(CreateView):
    queryset = Rate.objects.all()
    form_class = RateForm
    success_url = reverse_lazy('currency:rate-list')
    template_name = 'rate_create.html'


class ContactUsView(ListView):
    queryset = ContactUs.objects.all()
    template_name = 'contact_us.html'


# def contact_us(request):
#     contacts = ContactUs.objects.all()
#     context = {
#         'contact_us': contacts,
#     }
#
#     return render(request, 'contact_us.html', context=context)


class RateDetailView(LoginRequiredMixin, DetailView):
    queryset = Rate.objects.all()
    template_name = 'rate_details.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(id=self.request.user.id)
        return queryset


# def rate_details(request, rate_id):
#     """
#     try:
#         rate = Rate.objects.get(id=rate_id)
#     except Rate.DoesNotExist as exc:
#         raise Http404(exc)
#     """
#     rate = get_object_or_404(Rate, id=rate_id)
#     context = {
#         'object': rate,
#     }
#     return render(request, 'rate_details.html', context=context)

class RateUpdateView(UpdateView):
    queryset = Rate.objects.all()
    form_class = RateForm
    success_url = reverse_lazy('currency:rate-list')
    template_name = 'rate_update.html'


# def rate_update(request, rate_id):
#     rate = get_object_or_404(Rate, id=rate_id)
#
#     if request.method == 'POST':
#         form = RateForm(request.POST, instance=rate)
#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect('/rate/list/')
#     elif request.method == 'GET':
#         form = RateForm(instance=rate)
#     context = {
#         'form': form,
#     }
#     return render(request, 'rate_update.html', context=context)


class RateDeleteView(DeleteView):
    queryset = Rate.objects.all()
    form_class = RateForm
    success_url = reverse_lazy('currency:rate-list')
    template_name = 'rate_delete.html'


# def rate_delete(request, rate_id):
#     rate = get_object_or_404(Rate, id=rate_id)
#
#     if request.method == 'POST':
#         rate.delete()
#         return HttpResponseRedirect('/rate/list/')
#
#     # if request.method == 'GET'
#     context = {
#         'object': rate,
#     }
#     return render(request, 'rate_delete.html', context=context)


# Source
class SourceListView(ListView):
    queryset = Source.objects.all()
    template_name = 'source_list.html'


# def source_list(request):
#     sources = Source.objects.all()
#     context = {
#         'source_list': sources,
#     }
#     return render(request, 'source_list.html', context=context)


class SourceCreateView(CreateView):
    queryset = Source.objects.all()
    form_class = SourceForm
    success_url = reverse_lazy('source-list')
    template_name = 'source_create.html'


# def source_create(request):
#     if request.method == 'POST':
#         form = SourceForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect('/source/list/')
#     elif request.method == 'GET':
#         form = SourceForm()
#     context = {
#         'form': form,
#     }
#     return render(request, 'source_create.html', context=context)

class SourceUpdateView(UpdateView):
    queryset = Source.objects.all()
    form_class = SourceForm
    success_url = reverse_lazy('source-list')
    template_name = 'source_update.html'


# def source_update(request, source_id):
#     source = get_object_or_404(Source, id=source_id)
#
#     if request.method == 'POST':
#         form = SourceForm(request.POST, instance=source)
#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect('/source/list/')
#     elif request.method == 'GET':
#         form = SourceForm(instance=source)
#     context = {
#         'form': form,
#     }
#     return render(request, 'source_update.html', context=context)

class SourceDeleteView(DeleteView):
    queryset = Source.objects.all()
    form_class = SourceForm
    success_url = reverse_lazy('source-list')
    template_name = 'source_delete.html'


# def source_delete(request, source_id):
#     source = get_object_or_404(Source, id=source_id)
#
#     if request.method == 'POST':
#         source.delete()
#         return HttpResponseRedirect('/source/list/')
#
#     # if request.method == 'GET'
#     context = {
#         'object': source,
#     }
#     return render(request, 'source_delete.html', context=context)


def response_codes(request):
    response = HttpResponse('Response', status=301, headers={'Location': 'https://google.com'})
    return response

app/currency/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

{% include 'includes/navbar.html' %}


{% block main_content %}
{% include 'includes/footer.html' %}
{% endblock %}

</body>
</html>

app/currency/templates/contact_us.html
{% extends 'base.html' %}

{% block main_content %}


<table>
    <tr>
        <td>ID</td>
        <td>Email</td>
        <td>Subject</td>
    </tr>
    {% for contact in object_list %}
    <tr>
        <td>{{ contact.id }}</td>
        <td>{{ contact.email_form }}</td>
        <td>{{ contact.subject }}</td>
    </tr>
    {% endfor %}
</table>

{% endblock %}

app/currency/templates/contact_us_create.html
{% extends 'base.html' %}

{% block main_content %}

Contact Us

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
</form>

{% endblock %}

app/currency/templates/generate_password.html
{% extends 'base.html' %}

{% block main_content %}

Generate Password

Your password: {{ password }}

{% endblock %}

app/currency/templates/index.html
{% extends 'base.html' %}

{% block main_content %}




Hello from index
{% endblock %}

app/currency/templates/rate_create.html
{% extends 'base.html' %}

{% block main_content %}

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Send To Django Server</button>
</form>

{% endblock %}

app/currency/templates/rate_delete.html
{% extends 'base.html' %}

{% block main_content %}

Are you sure? The record with ID {{ object.id }} will not be restored.

<form method="post">
    {% csrf_token %}
    <button type="submit">Delete</button>
</form>

{% endblock %}

app/currency/templates/rate_details.html
{% extends 'base.html' %}

{% block main_content %}

Rate Details<br>

Id: {{ object.id }}<br>
Buy: {{ object.buy }}<br>
Sale: {{ object.sale }}<br>
Type: {{ object.type }}<br>
Source: {{ object.source }}<br>
Create: {{ object.created }}<br>




{% endblock %}

app/currency/templates/rate_list.html
{% extends 'base.html' %}

{% block main_content %}

<a href="{% url 'currency:rate-create' %}">Create Rate</a>
<br>

<table>
    <tr>
        <td>ID</td>
        <td>Sale</td>
        <td>Buy</td>
        <td>Type</td>
    </tr>
    {% for rate in rate_list %}
    <tr>
        <td>{{ rate.id }}</td>
        <td>{{ rate.sale}}</td>
        <td>{{ rate.buy}}</td>
        <td>{{ rate.type }}</td>
        <td><a href="{% url 'currency:rate-details' rate.pk %}">Details</a></td>
        <td><a href="{% url 'currency:rate-update' rate.pk %}">Update</a></td>
        <td><a href="{% url 'currency:rate-delete' rate.pk %}">Delete</a></td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

app/currency/templates/rate_update.html
{% extends 'base.html' %}

{% block main_content %}

UPDATE RATE

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Send To Django Server</button>
</form>

{% endblock %}

app/currency/templates/source_create.html
{% extends 'base.html' %}

{% block main_content %}

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Send To Django Server</button>
</form>

{% endblock %}

app/currency/templates/source_delete.html
{% extends 'base.html' %}

{% block main_content %}

Are you sure? The record with ID {{ object.id }} will not be restored.

<form method="post">
    {% csrf_token %}
    <button type="submit">Delete</button>
</form>

{% endblock %}

app/currency/templates/source_list.html
{% extends 'base.html' %}

{% block main_content %}

<a href="{% url 'source-create' %}">Create Source</a>
<br>

<table>
    <tr>
        <td>ID</td>
        <td>Name</td>
        <td>Source</td>
    </tr>
    {% for source in source_list %}
    <tr>
        <td>{{ source.id }}</td>
        <td>{{ source.name}}</td>
        <td>{{ source.source_url}}</td>
        <td><a href="{% url 'source-update' source.pk %}">Update</a></td>
        <td><a href="{% url 'source-delete' source.pk %}">Delete</a></td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

app/currency/templates/source_update.html
{% extends 'base.html' %}

{% block main_content %}

UPDATE SOURCE

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Send To Django Server</button>
</form>

{% endblock %}